import{initializeApp}from'https://www.gstatic.com/firebasejs/9.23.0/firebase-app.js';import{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut,setPersistence,browserLocalPersistence,GoogleAuthProvider,signInWithPopup}from'https://www.gstatic.com/firebasejs/9.23.0/firebase-auth.js';import{getFirestore,collection,doc,setDoc,getDoc,getDocs,updateDoc,addDoc,deleteDoc,onSnapshot,query,orderBy,limit,startAfter,serverTimestamp,increment,where,deleteField,Timestamp,arrayUnion,arrayRemove}from'https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js';import{getMessaging,getToken,onMessage}from'https://www.gstatic.com/firebasejs/9.23.0/firebase-messaging.js';import{getStorage,ref as storageRef,uploadBytes,getDownloadURL}from'https://www.gstatic.com/firebasejs/9.23.0/firebase-storage.js';const firebaseConfig={apiKey:"AIzaSyA9oat9dd0S9vlxkg1osH4dW3XhRDGiOiw",authDomain:"charlasrf4.firebaseapp.com",projectId:"charlasrf4",storageBucket:"charlasrf4.firebasestorage.app",messagingSenderId:"345019626508",appId:"1:345019626508:web:d099ca499acb29eac12a29"};const app=initializeApp(firebaseConfig);let _messaging=null;try{_messaging=getMessaging(app);}catch(e){}
const VAPID_KEY='BAqXiAE3JEYzG07fbtjywuXMM4887gnisTQnS6C14PXIVhUHXnc6JmPGb_C_VITzqnWYNm0lBpyVdcPDqFya83o';async function initPushNotifications(){if(!('Notification'in window)||!_messaging)return;try{const reg=await navigator.serviceWorker.register('/firebase-messaging-sw.js');console.log('[FCM] Service worker registrado');onMessage(_messaging,(payload)=>{const{title,body}=payload.notification||{};toast('🏆 '+(body||title||'Nuevo trofeo publicado'),'ok');});if(Notification.permission==='granted'){await _saveFCMToken(reg);}}catch(e){console.warn('[FCM] Error iniciando push:',e);}}
async function _saveFCMToken(swReg){if(!window.CU||!_messaging)return;try{const token=await getToken(_messaging,{vapidKey:VAPID_KEY,serviceWorkerRegistration:swReg});if(token){await setDoc(doc(db,'fcmTokens',window.CU.id),{token,userId:window.CU.id,nick:window.CU.nick||'?',updatedAt:new Date()},{merge:true});console.log('[FCM] Token guardado');}}catch(e){console.warn('[FCM] Error guardando token:',e);}}
window.requestPushPermission=async function(){if(!('Notification'in window)){toast('Tu navegador no soporta notificaciones','err');return;}
const perm=await Notification.requestPermission();if(perm==='granted'){const reg=await navigator.serviceWorker.getRegistration('/firebase-messaging-sw.js');if(reg)await _saveFCMToken(reg);toast('🔔 Notificaciones activadas','ok');}else{toast('Notificaciones bloqueadas','err');}};const storage=getStorage(app);const auth=getAuth(app);(async()=>{try{await setPersistence(auth,browserLocalPersistence);}catch(e){}})();const db=getFirestore(app);window.db=db;window._fsImports={collection,query,where,orderBy,onSnapshot,addDoc};window._fsLib={getDocs,query,collection,where,orderBy,limit,startAfter,onSnapshot,addDoc,serverTimestamp,doc,updateDoc,deleteDoc};window.firebaseFirestore={getDocs,query,collection,where,orderBy,limit,startAfter,onSnapshot,addDoc,serverTimestamp,doc,updateDoc,deleteDoc};window.getDocs=getDocs;window.collection=collection;window.doc=doc;window.setDoc=setDoc;window.getDoc=getDoc;window.deleteDoc=deleteDoc;window.onSnapshot=onSnapshot;window.query=query;window.where=where;window.orderBy=orderBy;window.limit=limit;window.addDoc=addDoc;window.updateDoc=updateDoc;window.serverTimestamp=serverTimestamp;window.CU=null;function isAdminUser(u){if(!u)return false;return u.role==='admin'||u.nick==='ruizgustavo12'||u.nick==='gustavo ruiz'||u.nick==='gustavoruiz'||u.email==='synxyes@gmail.com';}
function isAdminUid(uid){if(!uid)return false;const friends=window.CU?.friendsList||[];const f=friends.find(f=>f.id===uid);if(f&&isAdminUser(f))return true;return false;}
let _posts=[];let _stories=[];let _svIdx=0;let _storyEmojiPick='';let _postImgData=null;let _storyImgData=null;let _rxnTimers={};let _unsubPosts=null;let _unsubStories=null;const REACTIONS=[{emoji:'👍',label:'Me gusta',color:'#1877f2',lottieSegment:'Like'},{emoji:'❤️',label:'Me encanta',color:'#f33e58',lottieSegment:'Love'},{emoji:'😂',label:'Me divierte',color:'#f7b125',lottieSegment:'Haha'},{emoji:'😮',label:'Me asombra',color:'#f7b125',lottieSegment:'Wow'},{emoji:'😢',label:'Me entristece',color:'#6b9de8',lottieSegment:'Sad'},{emoji:'😡',label:'Me enoja',color:'#e9710f',lottieSegment:'Angry'},];window.REACTIONS=REACTIONS;window.REACTIONS=REACTIONS;const REACTION_CATEGORIES=[{cat:'',emojis:REACTIONS}];const REACTION_EMOJIS=REACTIONS.map(r=>r.emoji);const FISH_EMOJIS={'Pike':'🐟','Catfish':'🦈','Bream':'🐡','Perch':'🐠','Carp':'🐟','Trout':'🐟','Salmon':'🐟','Burbot':'🐟','Ruffe':'🐟','Tench':'🐟'};function save(k,v){try{localStorage.setItem('crf4_'+k,JSON.stringify(v));}catch(e){}}
function load(k,def){try{const v=localStorage.getItem('crf4_'+k);return v?JSON.parse(v):def;}catch(e){return def;}}
const CLOUDINARY_CLOUD='da0n5tg3g';const CLOUDINARY_PRESET='wikipediarf4';const CLOUDINARY_VIDEO_PRESET='milatido_video';function applyAdminUploadUnlock(){const isAdmin=window.CU&&(window.CU.role==='admin'||window.CU.nick==='ruizgustavo12'||window.CU.nick==='gustavo ruiz'||window.CU.nick==='gustavoruiz'||window.CU.email==='synxyes@gmail.com');if(!isAdmin)return;document.querySelectorAll('input[type="file"]').forEach(inp=>{inp.removeAttribute('accept');inp.setAttribute('accept','*/*');inp.removeAttribute('multiple');inp.setAttribute('multiple',true);});if(window._adminUploadObserver)return;window._adminUploadObserver=new MutationObserver(muts=>{muts.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType!==1)return;if(n.tagName==='INPUT'&&n.type==='file'){n.setAttribute('accept','*/*');n.setAttribute('multiple',true);}
n.querySelectorAll&&n.querySelectorAll('input[type="file"]').forEach(inp=>{inp.setAttribute('accept','*/*');inp.setAttribute('multiple',true);});}));});window._adminUploadObserver.observe(document.body,{childList:true,subtree:true});}
async function uploadImage(fileOrBase64,folder){let blob;if(typeof fileOrBase64==='string'&&fileOrBase64.startsWith('data:')){const res=await fetch(fileOrBase64);blob=await res.blob();}else if(typeof fileOrBase64==='string'){const res=await fetch(fileOrBase64);blob=await res.blob();}else{blob=fileOrBase64;}
if(blob.type.startsWith('image/')&&blob.size>800000){blob=await _compressImage(blob,1200,0.82);}
if(blob.type.startsWith('image/')&&folder&&folder.includes('trofeo')){blob=await _addWatermark(blob);}
const formData=new FormData();formData.append('file',blob);formData.append('upload_preset',CLOUDINARY_PRESET);formData.append('folder','rf4/'+(folder||'general'));let res,data;try{res=await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/image/upload`,{method:'POST',body:formData});data=await res.json();}catch(netErr){throw new Error('Sin conexión. Verificá tu red e intentá de nuevo.');}
if(res.ok&&data.secure_url)return data.secure_url;const errMsg=data?.error?.message||'';if(errMsg.toLowerCase().includes('preset')){throw new Error('El preset de Cloudinary no está configurado como Unsigned. Entrá a Settings → Upload → Upload presets → "'+CLOUDINARY_PRESET+'" → cambiá Signing mode a Unsigned.');}
throw new Error(errMsg||'Error al subir imagen. Intentá de nuevo.');}
function _addWatermark(blob){return new Promise((resolve)=>{const img=new Image();const url=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(url);const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);const text='www.milatido.uy';const fontSize=Math.max(20,Math.round(img.width*0.042));ctx.font=`bold ${fontSize}px Exo 2, Arial, sans-serif`;const padding=Math.round(fontSize*0.55);const textWidth=ctx.measureText(text).width;const boxW=textWidth+padding*2;const boxH=fontSize+padding*1.3;const x=img.width-boxW-14;const y=img.height-boxH-14;ctx.fillStyle='rgba(0, 0, 0, 0.62)';ctx.beginPath();ctx.roundRect(x,y,boxW,boxH,8);ctx.fill();ctx.strokeStyle='rgba(46,196,182,0.7)';ctx.lineWidth=1.5;ctx.beginPath();ctx.roundRect(x,y,boxW,boxH,8);ctx.stroke();const textX=x+padding;const textY=y+boxH-padding*0.65;ctx.shadowColor='rgba(0,0,0,0.8)';ctx.shadowBlur=6;ctx.shadowOffsetX=1;ctx.shadowOffsetY=1;const grad=ctx.createLinearGradient(textX,0,textX+textWidth,0);grad.addColorStop(0,'#2ec4b6');grad.addColorStop(0.4,'#ffffff');grad.addColorStop(0.7,'#ffd700');grad.addColorStop(1,'#2ec4b6');ctx.fillStyle=grad;ctx.fillText(text,textX,textY);ctx.shadowColor='transparent';ctx.shadowBlur=0;canvas.toBlob(b=>resolve(b||blob),'image/jpeg',0.93);};img.onerror=()=>{URL.revokeObjectURL(url);resolve(blob);};img.src=url;});}
function _compressImage(blob,maxW,quality){return new Promise((resolve)=>{const img=new Image();const url=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(url);const canvas=document.createElement('canvas');let w=img.width,h=img.height;if(w>maxW){h=Math.round(h*maxW/w);w=maxW;}
canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);canvas.toBlob(b=>resolve(b||blob),'image/jpeg',quality);};img.onerror=()=>{URL.revokeObjectURL(url);resolve(blob);};img.src=url;});}
async function uploadVideo(file,folder){const formData=new FormData();formData.append('file',file);formData.append('upload_preset',CLOUDINARY_VIDEO_PRESET);formData.append('folder','rf4/'+(folder||'videos'));formData.append('resource_type','video');const res=await fetch(`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/video/upload`,{method:'POST',body:formData});const data=await res.json();if(!data.secure_url)throw new Error(data.error?.message||'Error subiendo video');return data.secure_url;}
window._verifUsers={};window._usersShop={};let _usersLastFetch=0;async function listenVerifiedUsers(){if(Date.now()-_usersLastFetch<1800000&&Object.keys(window._verifUsers||{}).length>0)return;try{const snap=await getDocs(query(collection(db,'users'),limit(200)));window._verifUsers={};window._usersShop={};snap.docs.forEach(d=>{const data=d.data();if(data.verified===true)window._verifUsers[d.id]=true;window._usersShop[d.id]=data.shopEquipped||{};});_usersLastFetch=Date.now();}catch(e){console.warn('listenVerifiedUsers error:',e);}}
let _postsUnsub=null;let _postsRetryTimer=null;let _upPostsUnsub=null;const _postsLimit=20;let _lastPostDoc=null;let _loadingMore=false;let _noMorePosts=false;let _infiniteObserver=null;function _setupInfiniteScroll(){if(_infiniteObserver){_infiniteObserver.disconnect();_infiniteObserver=null;}
if(!('IntersectionObserver'in window))return;var sentinel=document.getElementById('_feedSentinel');if(!sentinel){sentinel=document.createElement('div');sentinel.id='_feedSentinel';sentinel.style.cssText='height:1px;width:100%;';}
const feedEl=document.getElementById('feedPosts');if(feedEl)feedEl.appendChild(sentinel);_infiniteObserver=new IntersectionObserver(function(entries){if(entries[0].isIntersecting&&!_loadingMore&&!_noMorePosts){_loadMorePosts();}},{rootMargin:'300px'});_infiniteObserver.observe(sentinel);}
async function _loadMorePosts(){if(_loadingMore||_noMorePosts||!_lastPostDoc)return;_loadingMore=true;const sentinel=document.getElementById('_feedSentinel');if(sentinel)sentinel.innerHTML='<div style="text-align:center;padding:20px;color:var(--muted);font-size:.82rem;">⏳ Cargando más...</div>';try{const{getDocs:_gd,query:_q,collection:_col,orderBy:_ob,limit:_lim,startAfter:_sa}=window._fsLib||{};if(!_gd)throw new Error('fsLib no disponible');const snap=await _gd(_q(_col(db,'posts'),_ob('time','desc'),_sa(_lastPostDoc),_lim(_postsLimit)));if(snap.empty||snap.docs.length===0){_noMorePosts=true;if(sentinel)sentinel.innerHTML='<div style="text-align:center;padding:20px;color:var(--muted);font-size:.75rem;">— No hay más posts —</div>';_loadingMore=false;return;}
_lastPostDoc=snap.docs[snap.docs.length-1];const newPosts=snap.docs.map(d=>({id:d.id,...d.data(),time:d.data().time?.toMillis?.()||Date.now()}));const existingIds=new Set(_posts.map(p=>p.id));const toAdd=newPosts.filter(p=>!existingIds.has(p.id));_posts=_posts.concat(toAdd);const feedEl=document.getElementById('feedPosts');const isPremium=true;if(feedEl){toAdd.forEach(function(p,i){const tmp=document.createElement('div');tmp.innerHTML=postHTML(p);const node=tmp.firstElementChild;if(node)feedEl.insertBefore(node,sentinel);});toAdd.forEach(function(p){if(p.id){registerPostView(p.id);subscribePostViews(p.id);}});}
if(sentinel)sentinel.innerHTML='<div style="height:1px;"></div>';}catch(e){console.warn('loadMorePosts error:',e);if(sentinel)sentinel.innerHTML='';}
_loadingMore=false;}
function listenPosts(){if(_postsUnsub){_postsUnsub();_postsUnsub=null;}
if(_postsRetryTimer){clearTimeout(_postsRetryTimer);_postsRetryTimer=null;}
_lastPostDoc=null;_loadingMore=false;_noMorePosts=false;const feedEl=document.getElementById('feedPosts');if(feedEl&&feedEl.innerHTML.includes('Cargando feed')){feedEl.innerHTML='<div style="text-align:center;padding:40px;color:var(--muted);font-size:.85rem;">⏳ Conectando...</div>';}
_postsUnsub=onSnapshot(query(collection(db,'posts'),orderBy('time','desc'),limit(_postsLimit)),{includeMetadataChanges:false},snap=>{if(snap.metadata.fromCache&&_posts&&_posts.length>0)return;if(snap.docs.length>0)_lastPostDoc=snap.docs[snap.docs.length-1];_noMorePosts=snap.docs.length<_postsLimit;_posts=snap.docs.map(d=>({id:d.id,...d.data(),time:d.data().time?.toMillis?.()||Date.now()}));const activePage=document.querySelector('.page.active');const pageId=activePage?activePage.id:'';if(pageId==='page-profile'){renderProfileFeed();}
else{const feedEl=document.getElementById('feedPosts');if(feedEl&&_posts.length){const banner=feedEl.querySelector('[data-popular-banner]');if(banner)banner.remove();}
renderFeed();setTimeout(_setupInfiniteScroll,300);}},err=>{console.warn('listenPosts error:',err);getDocs(query(collection(db,'posts'),orderBy('time','desc'),limit(_postsLimit))).then(snap=>{if(snap.docs.length>0)_lastPostDoc=snap.docs[snap.docs.length-1];_posts=snap.docs.map(d=>({id:d.id,...d.data(),time:d.data().time?.toMillis?.()||Date.now()})).sort((a,b)=>b.time-a.time).slice(0,_postsLimit);renderFeed();setTimeout(_setupInfiniteScroll,300);}).catch(e2=>{console.error('listenPosts fallback error:',e2);const el2=document.getElementById('feedPosts');if(el2)el2.innerHTML='<div style="text-align:center;padding:40px;color:var(--muted);font-size:.85rem;">⚠️ Error al cargar el feed.<br><button onclick="listenPosts()" style="margin-top:12px;background:var(--accent);color:#000;border:none;border-radius:8px;padding:8px 20px;font-size:.82rem;font-weight:700;cursor:pointer;">🔄 Reintentar</button></div>';});_postsRetryTimer=setTimeout(()=>{listenPosts();},15000);});}
let _storiesUnsub=null;function listenStories(){if(_storiesUnsub){_storiesUnsub();_storiesUnsub=null;}
_storiesUnsub=onSnapshot(query(collection(db,'stories'),orderBy('time','desc'),limit(80)),{includeMetadataChanges:false},snap=>{const now=Date.now();const expiredIds=[];_stories=snap.docs.filter(d=>{const data=d.data();if(data.expiresAt){const exp=data.expiresAt?.toMillis?data.expiresAt.toMillis():(data.expiresAt instanceof Date?data.expiresAt.getTime():new Date(data.expiresAt).getTime());if(exp&&exp<now){expiredIds.push(d.id);return false;}
return true;}
const raw=data.time;const t=raw?.toMillis?raw.toMillis():(typeof raw==='number'?raw:0);const ttl=data.userVerified?172800000:86400000;if(t===0)return true;if((now-t)>ttl){expiredIds.push(d.id);return false;}
return true;}).map(d=>{const raw=d.data().time;const t=raw?.toMillis?raw.toMillis():(typeof raw==='number'?raw:Date.now());return{id:d.id,...d.data(),time:t};});if(!snap.metadata.hasPendingWrites&&expiredIds.length){expiredIds.forEach(id=>{deleteDoc(doc(db,'stories',id)).catch(()=>{});});}
renderStories();},err=>{console.warn('listenStories error:',err);});}
function init(){setTimeout(()=>{const s=document.getElementById('splash');if(s){s.classList.add('hide');setTimeout(()=>s.remove(),500);}},1000);loadSavedAccounts();const _splashTimeout=setTimeout(()=>{const splash=document.getElementById('splashScreen');if(splash&&splash.style.display!=='none'){splash.style.display='none';if(!window.CU){var authEl=document.getElementById('mAuth');if(authEl){authEl.style.display='block';authEl.style.zIndex='100000';}}}},6000);onAuthStateChanged(auth,async user=>{clearTimeout(_splashTimeout);const splash=document.getElementById('splashScreen');const hideSplash=()=>{if(splash)splash.style.display='none';};if(user){try{const snap=await getDoc(doc(db,'users',user.uid));if(snap.exists()){window.CU={id:user.uid,...snap.data()};applyAdminUploadUnlock();setTimeout(()=>{if(typeof window._updateStoryCard==='function')window._updateStoryCard();},100);setTimeout(()=>{if(typeof window._updateStoryCard==='function')window._updateStoryCard();},2000);if(window._cuDocUnsub)window._cuDocUnsub();window._cuDocUnsub=onSnapshot(doc(db,'users',user.uid),dsnap=>{if(!dsnap.exists())return;const data=dsnap.data();if(data.av&&window.CU){window.CU.av=data.av;if(typeof window._updateStoryCard==='function')window._updateStoryCard();}});if(window.CU.role==='premium'&&window.CU.premiumReason==='auto_5trofeos'&&window.CU.premiumExpiry){const expiry=new Date(window.CU.premiumExpiry);if(new Date()>expiry){try{await updateDoc(doc(db,'users',user.uid),{role:'pescador',premiumExpired:true});window.CU.role='pescador';setTimeout(function(){toast('⭐ Tu Premium de 15 días venció. ¡Suscribite por $1/mes para seguir disfrutando los beneficios!','inf');setTimeout(openPremiumModal,2500);},2000);}catch(e){console.warn('Expiry check error:',e);}}}
if(window.CU.banned){await signOut(auth);hideSplash();_showBanScreen(window.CU.banReason,window.CU.banNote);return;}
if(window._userInfoCache)window._userInfoCache[user.uid]={nick:window.CU.nick||'',av:window.CU.av||'',gender:window.CU.gender||'',country:window.CU.country||''};const _isAdmin=window.CU.nick==='ruizgustavo12'||window.CU.nick==='gustavo ruiz'||window.CU.nick==='gustavoruiz'||window.CU.email==='synxyes@gmail.com'||window.CU.role==='admin';document.getElementById('mAuth').style.display='none';hideSplash();if(_isAdmin&&window._hideConstruction)window._hideConstruction();if(!window.CU.country){window._pendingGoogleOnboard=false;const cpModal=document.getElementById('mCountryPick');if(cpModal){cpModal.style.display='flex';}}else{onLogin();}}else{hideSplash();const _isAdminByEmail=user.email==='synxyes@gmail.com';if(_isAdminByEmail&&window._hideConstruction){window.CU={id:user.uid,email:user.email,nick:'ruizgustavo12',role:'admin'};window._hideConstruction();if(typeof onLogin==='function')onLogin();}}}catch(e){console.error('Auth error:',e);hideSplash();if(!window.CU){var authEl=document.getElementById('mAuth');if(authEl){authEl.style.display='block';authEl.style.zIndex='100000';}}}}else{window.CU=null;hideSplash();var authEl=document.getElementById('mAuth');if(authEl){authEl.style.display='block';authEl.style.zIndex='100000';}}});}
function toast(msg,type='inf'){const ct=document.getElementById('toastCt');if(!ct)return;const t=document.createElement('div');t.className=`toast ${type}`;const icon=type==='ok'?'✅':type==='err'?'❌':'ℹ️';t.innerHTML=`<span>${icon}</span><span>${msg}</span>`;ct.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transform='translateX(20px)';t.style.transition='all .3s';setTimeout(()=>t.remove(),300);},3000);}
function fmtT(ts){if(!ts)return'';const ms=ts?.toMillis?ts.toMillis():(typeof ts==='number'?ts:0);if(!ms)return'';const d=new Date(ms),now=Date.now(),diff=now-d.getTime();if(diff<0)return'Ahora';if(diff<60000)return'Ahora';if(diff<3600000)return Math.floor(diff/60000)+'m';if(diff<86400000)return Math.floor(diff/3600000)+'h';const meses=['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'];const dia=d.getDate();const mes=meses[d.getMonth()];const anio=d.getFullYear();const hora=String(d.getHours()).padStart(2,'0');const min=String(d.getMinutes()).padStart(2,'0');return`${dia} ${mes} ${anio} · ${hora}:${min}`;}
function esc(s){return(s==null?'':String(s)).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function fmtKg(w){var n=parseFloat(w)||0;return n>=1?n.toFixed(3)+' kg':Math.round(n*1000)+' g';}
function renderCommentText(text){if(!text)return'';const escaped=esc(text);return escaped.replace(/@(\w{2,30})/g,(match,nick)=>{return'<span style="color:var(--accent);font-weight:700;cursor:pointer;" onclick="searchMentionedUser(\''+nick+'\')">'+'@'+nick+'</span>';});}
async function searchMentionedUser(nick){if(!nick)return;try{const snap=await getDocs(query(collection(db,'users'),where('nickLower','==',nick.toLowerCase()),limit(1)));const user=snap.docs.length?{id:snap.docs[0].id,...snap.docs[0].data()}:null;if(user)openUserProfile(user.id,user.nick);else toast('@'+nick+' no encontrado','err');}catch(e){toast('Error buscando usuario','err');}}
function showNotifToast(text){const ct=document.getElementById('toastCt');if(!ct)return;const isMsg=text?.startsWith('💬');const t=document.createElement('div');t.className='toast ok';t.style.cssText='display:flex;gap:8px;align-items:center;max-width:300px;cursor:pointer;';t.innerHTML=(isMsg?'<span>💬</span>':'<span>🔔</span>')+'<span style="font-size:.82rem;flex:1;">'+text.slice(0,80)+'</span>';t.onclick=()=>{t.remove();if(isMsg){openMessenger();}else{openNotifDropdown();}};ct.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transition='opacity .4s';setTimeout(()=>t.remove(),400);},4000);}
function getDemoFriends(){return window.CU?.friendsList||[];}
async function doGoogleLogin(){const errEl=document.getElementById('lErr');errEl.textContent='';errEl.style.display='none';try{const provider=new GoogleAuthProvider();const cred=await signInWithPopup(auth,provider);const user=cred.user;const userRef=doc(db,'users',user.uid);const userSnap=await getDoc(userRef);if(!userSnap.exists()){const nick=(user.displayName?.replace(/\s+/g,'')||'User'+Date.now().toString().slice(-4));const newUser={nick,nickLower:nick.toLowerCase(),email:user.email,av:user.photoURL||'',cover:'',bio:'',country:'',favFish:'',favMap:'',social_yt:'',social_dc:'',joined:new Date().toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit',year:'numeric'}),posts:0,friends:0,likes:0,createdAt:serverTimestamp()};await setDoc(userRef,newUser);window.CU={id:user.uid,...newUser};document.getElementById('mAuth').style.display='none';window._pendingGoogleOnboard=true;const cpModal=document.getElementById('mCountryPick');if(cpModal){cpModal.style.display='flex';}
return;}else{window.CU={id:user.uid,...userSnap.data()};}
const _isAdminGoogle=window.CU.email==='synxyes@gmail.com'||window.CU.nick==='ruizgustavo12'||window.CU.nick==='gustavo ruiz'||window.CU.nick==='gustavoruiz'||window.CU.role==='admin';if(!window.CU.country&&!_isAdminGoogle){document.getElementById('mAuth').style.display='none';window._pendingGoogleOnboard=false;const cpModal=document.getElementById('mCountryPick');if(cpModal){cpModal.style.display='flex';}
return;}
document.getElementById('mAuth').style.display='none';if(_isAdminGoogle&&window._hideConstruction)window._hideConstruction();onLogin();toast('¡Bienvenido '+(window.CU.nick||'Admin')+'! '+(_isAdminGoogle?'🛡️':'🎣'),'ok');}catch(e){if(e.code==='auth/popup-closed-by-user'||e.code==='auth/cancelled-popup-request')return;let gMsg=e.message||'Error desconocido';if(e.code==='auth/unauthorized-domain'){gMsg='⚠️ Dominio no autorizado en Firebase. Agregá este dominio en Firebase Console → Authentication → Settings → Authorized domains.';}else if(e.code==='auth/operation-not-allowed'){gMsg='⚠️ Google Sign-In no está habilitado. Activalo en Firebase Console → Authentication → Sign-in methods → Google.';}else if(e.code==='auth/popup-blocked'){gMsg='⚠️ El navegador bloqueó la ventana emergente. Permití popups para este sitio e intentá de nuevo.';}else if(e.code==='auth/network-request-failed'){gMsg='⚠️ Error de red. Verificá tu conexión a internet.';}
errEl.style.display='block';errEl.textContent=gMsg;console.error('Google login error:',e.code,e.message);}}
window.confirmCountryPick=async function(){const sel=document.getElementById('cpCountrySelect');const errEl=document.getElementById('cpErr');const country=sel?sel.value.trim():'';if(!country){if(errEl){errEl.style.display='block';}return;}
if(errEl)errEl.style.display='none';try{if(window.CU?.id){const{doc:_doc,updateDoc:_upd}=await import('https://www.gstatic.com/firebasejs/9.23.0/firebase-firestore.js');await _upd(_doc(db,'users',window.CU.id),{country});window.CU.country=country;}
const cpModal=document.getElementById('mCountryPick');if(cpModal)cpModal.style.display='none';onLogin();toast('¡Bienvenido '+window.CU.nick+'! 🎣','ok');}catch(e){if(window.CU)window.CU.country=country;const cpModal=document.getElementById('mCountryPick');if(cpModal)cpModal.style.display='none';onLogin();toast('¡Bienvenido '+window.CU.nick+'! 🎣','ok');}};async function doLogin(){let input=document.getElementById('lEmail').value.trim();const pw=document.getElementById('lPass').value;const errEl=document.getElementById('lErr');const btn=document.getElementById('loginBtn');errEl.textContent='';errEl.style.display='none';if(!input||!pw){errEl.textContent='Completa todos los campos';errEl.style.display='block';return;}
if(btn){btn.disabled=true;btn.textContent='Iniciando...';}
if(!input.includes('@')){try{const nickLower=input.toLowerCase();let found=null;try{const q=await getDocs(query(collection(db,'users'),where('nickLower','==',nickLower)));if(q&&!q.empty)found=q.docs[0];}catch(e2){console.warn('nickLower query error:',e2);}
if(!found){try{const q2=await getDocs(query(collection(db,'users'),where('nick','==',input)));if(q2&&!q2.empty)found=q2.docs[0];}catch(e3){console.warn('nick query error:',e3);}}
if(!found){try{const all=await getDocs(query(collection(db,'users'),limit(50)));found=all.docs.find(d=>{const n=d.data().nick||'';const nl=d.data().nickLower||'';return n===input||nl===nickLower||n.toLowerCase()===nickLower;});}catch(e4){console.warn('scan error:',e4);}}
if(!found){errEl.textContent='Nick no encontrado. Probá con tu email.';errEl.style.display='block';if(btn){btn.disabled=false;btn.textContent='Iniciar sesión';}
return;}
input=found.data().email;if(!input){errEl.textContent='No se pudo obtener el email de este nick';errEl.style.display='block';if(btn){btn.disabled=false;btn.textContent='Iniciar sesión';}
return;}}catch(e){errEl.textContent='Error de conexión. Reintentá.';errEl.style.display='block';if(btn){btn.disabled=false;btn.textContent='Iniciar sesión';}
return;}}
try{const remember=document.getElementById('rememberMe')?.checked!==false;const cred=await signInWithEmailAndPassword(auth,input,pw);const snap=await getDoc(doc(db,'users',cred.user.uid));if(!snap.exists()){const _adminEmails=['synxyes@gmail.com'];if(_adminEmails.includes(cred.user.email)){window.CU={id:cred.user.uid,email:cred.user.email,nick:'ruizgustavo12',role:'admin',country:'UY'};document.getElementById('mAuth').style.display='none';if(window._hideConstruction)window._hideConstruction();onLogin();toast('¡Bienvenido Admin! 🛡️','ok');return;}
errEl.textContent='Cuenta no encontrada en la base de datos.';if(btn){btn.disabled=false;btn.textContent='Iniciar sesión';}
return;}
const userData=snap.data();if(userData.banned){await signOut(auth);_showBanScreen(userData.banReason,userData.banNote);if(btn){btn.disabled=false;btn.textContent='Iniciar sesión';}
return;}
window.CU={id:cred.user.uid,...userData};saveAccountLocally(input,window.CU.nick,pw,window.CU.av||'');document.getElementById('mAuth').style.display='none';if(window._hideConstruction)window._hideConstruction();onLogin();toast('¡Bienvenido '+window.CU.nick+'! 🎣','ok');}catch(e){let msg='Error: '+(e.code||e.message||'desconocido');if(e.code==='auth/invalid-email')msg='Email inválido';else if(e.code==='auth/user-not-found')msg='Usuario no encontrado. Verificá el email.';else if(e.code==='auth/wrong-password')msg='Contraseña incorrecta';else if(e.code==='auth/invalid-credential')msg='Email o contraseña incorrectos. Verificá bien los datos.';else if(e.code==='auth/invalid-login-credentials')msg='Email o contraseña incorrectos. Verificá bien los datos o usá ¿Olvidaste tu contraseña?';else if(e.code==='auth/user-disabled')msg='Esta cuenta fue deshabilitada.';else if(e.code==='auth/too-many-requests')msg='Demasiados intentos. Esperá unos minutos.';else if(e.code==='auth/network-request-failed')msg='Error de red. Verificá tu conexión.';else if(e.code==='auth/operation-not-allowed')msg='⚠️ Login con email no está habilitado en Firebase. Activalo en Firebase Console → Authentication → Sign-in methods.';else if(e.code==='auth/configuration-not-found')msg='⚠️ Firebase no está configurado para email/contraseña. Activalo en Firebase Console.';errEl.textContent=msg;errEl.style.display='block';console.error('Login error:',e.code,e.message);if(btn){btn.disabled=false;btn.textContent='Iniciar sesión';}}}
async function doReg(){const nick=document.getElementById('rNick').value.trim();const em=document.getElementById('rEmail').value.trim();const pw=document.getElementById('rPass').value;const country=document.getElementById('rCountry').value;const rErrEl=document.getElementById('rErr');rErrEl.textContent='';rErrEl.style.display='none';if(!nick||!em||!pw){document.getElementById('rErr').textContent='Completa los campos obligatorios';return;}
if(pw.length<6){document.getElementById('rErr').textContent='Mínimo 6 caracteres';return;}
if(!document.getElementById('acceptTerms')?.checked){document.getElementById('rErr').textContent='Debés aceptar los Términos y Condiciones';return;}
try{const banSnap=await getDoc(doc(db,'bannedEmails',em.toLowerCase().replace(/\./g,'_')));if(banSnap.exists()){rErrEl.textContent='⛔ Este email no puede ser usado para crear una cuenta.';rErrEl.style.display='block';return;}}catch(e){}
try{const cred=await createUserWithEmailAndPassword(auth,em,pw);window.CU={id:cred.user.uid,nick,nickLower:nick.toLowerCase(),email:em,country,av:'',cover:'',bio:'',favFish:'',favMap:'',social_yt:'',social_dc:'',joined:new Date().toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit',year:'numeric'}),posts:0,friends:0,likes:0,regTs:Date.now()};await setDoc(doc(db,'users',cred.user.uid),window.CU);document.getElementById('mAuth').style.display='none';if(window._hideConstruction)window._hideConstruction();onLogin();setTimeout(_startPhotoTimer,500);toast('¡Bienvenido '+nick+'! 🎣','ok');}catch(e){document.getElementById('rErr').textContent=e.code==='auth/email-already-in-use'?'Email ya registrado':e.message;}}
function onLogin(){if(typeof tiendaCheckAdmin==='function')setTimeout(tiendaCheckAdmin,200);setTimeout(async()=>{await initPushNotifications();if(Notification.permission==='granted'){const btn=document.getElementById('pushNotifMenuItem');if(btn)btn.innerHTML='🔔 Notificaciones activadas ✓';}},2000);updateNavUI();listenPosts();listenStories();listenVerifiedUsers().catch(e=>console.warn('listenVerifiedUsers error:',e));startPresence().then(()=>{if(typeof updatePresenceActivity==='function')updatePresenceActivity('home');});listenNotifs();setTimeout(()=>{loadRealFriends().then(()=>{renderProfile();renderSidebarFriends();});},300);setTimeout(()=>{loadPezSemana();loadShopEquipped();if(typeof _updatePostBoxPlaceholder==='function')_updatePostBoxPlaceholder();},800);setTimeout(()=>{renderSuggestedUsers();renderNewFishers();listenLive();renderSuggestedPosts();renderFriendSpotsInHome();checkDailyStreak();loadXPLevels();window.loadAdsIfNeeded&&window.loadAdsIfNeeded();},1500);setTimeout(async()=>{checkFriendsBirthdays();if(typeof window._checkChangelog==='function')window._checkChangelog();if(typeof loadMemories==='function')loadMemories();if(!window.CU?.id)return;try{const snap=await getDocs(query(collection(db,'stories'),where('userId','==',window.CU.id)));const now=Date.now();snap.docs.forEach(d=>{const raw=d.data().time;const t=raw?.toMillis?raw.toMillis():(typeof raw==='number'?raw:0);const ttl=d.data().userVerified?172800000:86400000;if(t&&(now-t)>ttl)deleteDoc(doc(db,'stories',d.id)).catch(()=>{});});}catch(e){}},3000);const wkPub=document.getElementById('wkNbPublish');if(wkPub)wkPub.style.display='';if(window.CU&&(window.CU.role==='admin'||(typeof WK_ADMIN!=='undefined'&&window.CU.nick===WK_ADMIN))){const wkAdm=document.getElementById('wkNbAdmin');if(wkAdm)wkAdm.style.display='';}
function _updateStoryCard(){const storyPhoto=document.getElementById('storyAddPhoto');if(!storyPhoto||!window.CU)return;window._storyCardFilled=true;if(window.CU.av){storyPhoto.innerHTML=`<img src="${window.CU.av}" style="width:100%;height:100%;object-fit:cover;border-radius:inherit;" onerror="this.style.display='none'">`;}else{const ini=(window.CU.nick||'?')[0].toUpperCase();storyPhoto.innerHTML=`<span style="font-size:3.5rem;opacity:.7;font-weight:800;color:var(--accent);">${ini}</span>`;}}
_updateStoryCard();setTimeout(_updateStoryCard,800);setTimeout(_updateStoryCard,2500);window._updateStoryCard=_updateStoryCard;loadSavedAccounts();const _initPath=window._initialPath||window.location.pathname;window._initialPath=null;window._initialRoute=null;if(_initPath&&_initPath!=='/'&&_initPath!=='/home'){setTimeout(()=>{if(!_initPath.startsWith('/u/')&&!_initPath.startsWith('/mensajes')&&!_initPath.startsWith('/notif')&&ROUTES[_initPath]===undefined&&_initPath.length>1&&!_initPath.includes('.')){const nickSlugLegacy=_initPath.slice(1);window.gp('userprofile',false);getDocs(query(collection(db,'users'),limit(100))).then(snap=>{const found=snap.docs.find(d=>{const n=(d.data().nick||'').toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');return n===nickSlugLegacy;});if(found){_loadUserProfilePage(found.id,found.data().nick||nickSlugLegacy);history.replaceState({page:'userprofile',uid:found.id,nick:found.data().nick},'','/u/'+nickSlugLegacy);}else{window.gp('home',false);}}).catch(()=>{window.gp('home',false);});return;}
if(_initPath.startsWith('/u/')){const nickSlug=_initPath.slice(3);window.gp('userprofile',false);getDocs(query(collection(db,'users'),limit(100))).then(snap=>{const found=snap.docs.find(d=>{const n=(d.data().nick||'').toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');return n===nickSlug;});if(found)_loadUserProfilePage(found.id,found.data().nick||nickSlug);}).catch(()=>{});return;}
if(_initPath.startsWith('/mensajes/')){om('mMessenger');renderMessengerList();return;}
if(_initPath==='/mensajes'){om('mMessenger');renderMessengerList();return;}
if(_initPath==='/notificaciones'){openNotifDropdown();return;}
const pageId=ROUTES[_initPath];if(pageId&&pageId!=='home')window.gp(pageId,false);},600);}
(function _checkProfilePhotoTimer(){if(!window.CU)return;if(window.CU.av&&typeof window.CU.av==='string'&&window.CU.av.startsWith('http'))return;const PHOTO_KEY='rf4_photo_deadline_'+window.CU.id;let deadline=localStorage.getItem(PHOTO_KEY);if(!deadline){deadline=Date.now()+10*60*1000;localStorage.setItem(PHOTO_KEY,deadline);}
deadline=parseInt(deadline);function _showPhotoModal(){if(document.getElementById('_photoRequiredModal'))return;const overlay=document.createElement('div');overlay.id='_photoRequiredModal';overlay.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:999999;display:flex;align-items:center;justify-content:center;backdrop-filter:blur(4px);';overlay.innerHTML=`
        <div style="background:#fff;border-radius:18px;padding:32px 28px;max-width:380px;width:90%;text-align:center;box-shadow:0 8px 40px rgba(0,0,0,.35);animation:mIn .3s ease;">
          <div style="font-size:3rem;margin-bottom:10px;">📸</div>
          <div style="font-family:'Orbitron',monospace;font-size:1.1rem;font-weight:900;color:#1a1a2e;margin-bottom:8px;">¡Foto de perfil requerida!</div>
          <div style="font-size:.88rem;color:#5a6478;line-height:1.6;margin-bottom:20px;">
            Para seguir usando la plataforma necesitás subir una foto de perfil.<br>
            <strong style="color:#2ec4b6;">¡Además obtenés el badge de usuario verificado! ✅</strong>
          </div>
          <button onclick="document.getElementById('_photoRequiredModal').style.display='none';window.gp('profile');setTimeout(()=>document.getElementById('profAvEdit')?.click(),600);"
            style="width:100%;padding:13px;background:linear-gradient(135deg,#2ec4b6,#25a99d);color:#fff;border:none;border-radius:10px;font-size:1rem;font-weight:800;cursor:pointer;font-family:'Exo 2',sans-serif;letter-spacing:.03em;">
            📷 Subir foto ahora
          </button>
          <div style="font-size:.72rem;color:#9aa0ab;margin-top:12px;">Sin foto no podés acceder a las funciones de Match ni al feed completo.</div>
        </div>`;document.body.appendChild(overlay);}
const remaining=deadline-Date.now();if(remaining<=0){setTimeout(_showPhotoModal,1500);}else{setTimeout(function(){if(!window.CU?.av||!window.CU.av.startsWith('http')){_showPhotoModal();}},remaining);}})();}
function _startPhotoTimer(){if(!window.CU)return;if(window.CU.av&&window.CU.av.startsWith('http'))return;const PHOTO_KEY='rf4_photo_deadline_'+window.CU.id;if(!localStorage.getItem(PHOTO_KEY)){localStorage.setItem(PHOTO_KEY,Date.now()+10*60*1000);}}
async function loadRealFriends(){if(!window.CU)return;const friendIds=window.CU.friends||[];if(!friendIds.length){window.CU.friendsList=[];renderSidebarFriends();return;}
try{const snaps=await Promise.all(friendIds.map(id=>getDoc(doc(db,'users',id))));window.CU.friendsList=snaps.filter(s=>s.exists()).map(s=>({id:s.id,...s.data()}));}catch(e){window.CU.friendsList=[];}
renderSidebarFriends();renderSuggestedUsers();renderNewFishers();renderSuggestedPosts();if(typeof listenUnreadMsgsBadge==='function')listenUnreadMsgsBadge();}
function updateNavUI(){const footer=document.getElementById('siteFooter');if(footer)footer.style.display='block';if(!window.CU)return;const av=`<img src="${window.CU.av||getDefaultAv(window.CU.gender||'')}" style="width:100%;height:100%;object-fit:cover;border-radius:50%;">`;document.getElementById('navAv').innerHTML=av;document.getElementById('slAv').innerHTML=av;document.getElementById('slName').textContent=window.CU.nick;document.getElementById('pbAv').innerHTML=av;if(document.getElementById('pbAv2'))document.getElementById('pbAv2').innerHTML=av;document.getElementById('cpAv').innerHTML=av;document.getElementById('cpName').textContent=window.CU.nick;document.getElementById('userMenuNick').textContent=window.CU.nick;document.getElementById('userMenuEmail').textContent=window.CU.email||'';const isAdmin=window.CU.nick==='ruizgustavo12'||window.CU.nick==='gustavo ruiz'||window.CU.nick==='gustavoruiz'||window.CU.email==='synxyes@gmail.com';const adminNavBtn=document.getElementById('adminNavBtn');const userMenuAdmin=document.getElementById('userMenuAdmin');const shopNavBtn=document.getElementById('shopNavBtn');if(adminNavBtn)adminNavBtn.style.display=isAdmin?'inline-flex':'none';if(userMenuAdmin)userMenuAdmin.style.display=isAdmin?'flex':'none';if(shopNavBtn)shopNavBtn.style.display='inline-flex';}
function renderShopPage(){renderShopGrid();setTimeout(initShopCoinsDisplay,400);if(typeof renderShopItems==='function')renderShopItems();}
function showReg(){document.getElementById('authForm').style.display='none';document.getElementById('regForm').style.display='block';}
function showLogin(){document.getElementById('authForm').style.display='block';document.getElementById('regForm').style.display='none';}
function showTerms(){document.getElementById('mTerms').style.display='block';document.getElementById('mTerms').scrollTop=0;}
function closeTerms(){document.getElementById('mTerms').style.display='none';}
function acceptTermsAndRegister(){const cb=document.getElementById('acceptTerms');if(cb)cb.checked=true;closeTerms();showReg();}
const ROUTES={'/':'home','/home':'home','/':'home','':'home','/home':'home','/amigos':'amigos','/tienda':'shop','/reels':'reels','/galeria':'galeria','/videos':'videos','/skill':'skill','/spots':'spots','/torneos':'torneos','/ranking-semanal':'ranking-semanal','/perfil':'profile','/parches':'parches','/soporte':'soporte','/mensajes':'mensajes','/notificaciones':'notificaciones','/pez-semanal':'pez-semanal','/privacidad':'privacidad',};const PAGE_TO_URL={'home':'/','amigos':'/amigos','shop':'/tienda','compartir-spot':'/compartir-spot','reels':'/reels','galeria':'/galeria','videos':'/videos','skill':'/skill','spots':'/spots','torneos':'/torneos','ranking-semanal':'/ranking-semanal','profile':'/perfil','parches':'/parches','soporte':'/soporte','mensajes':'/mensajes','notificaciones':'/notificaciones','pez-semanal':'/pez-semanal','admin':'/admin','grupos':'/grupos',};function navigateTo(id,pushState=true){if(!pushState)return;const url=PAGE_TO_URL[id];if(url){history.pushState({page:id},'',url);}}
window.addEventListener('popstate',(e)=>{const path=window.location.pathname;if(path!=='/mensajes'&&!path.startsWith('/mensajes/')){const msg=document.getElementById('mMessenger');if(msg&&msg.classList.contains('open'))msg.classList.remove('open');}
if(path!=='/notificaciones'){const nd=document.getElementById('mNotif');if(nd)nd.style.display='none';}
if(path.startsWith('/u/')){const nickSlug=path.slice('/u/'.length);if(window.CU){window.gp('userprofile',false);if(e.state&&e.state.uid){_loadUserProfilePage(e.state.uid,e.state.nick||nickSlug);}}
return;}
if(path.startsWith('/mensajes/')){const msgEl=document.getElementById('mMessenger');if(msgEl){om('mMessenger');renderMessengerList();}
if(e.state&&e.state.chatUid)openChatWith(e.state.chatUid,e.state.chatNick||'');return;}
if(path==='/mensajes'){const msgEl=document.getElementById('mMessenger');if(msgEl){om('mMessenger');renderMessengerList();}
return;}
if(path==='/notificaciones'){openNotifDropdown();return;}
const pageId=ROUTES[path];if(pageId){window.gp(pageId,false);}else if(path.length>1&&!path.includes('.')){const nickSlug=path.slice(1);if(window.CU&&e.state&&e.state.uid){window.gp('userprofile',false);_loadUserProfilePage(e.state.uid,e.state.nick||nickSlug);}else{window.gp('home',false);}}else{window.gp('home',false);}});window.addEventListener('DOMContentLoaded',()=>{const rParam=new URLSearchParams(window.location.search).get('r');if(rParam){const redirectPath=decodeURIComponent(rParam);if(redirectPath!=='/'&&redirectPath!=='/home'){history.replaceState(null,'',redirectPath);}}else{const redirectPath=sessionStorage.getItem('__rf4_redirect');if(redirectPath){sessionStorage.removeItem('__rf4_redirect');if(redirectPath!=='/'&&redirectPath!=='/home'){history.replaceState(null,'',redirectPath);}}}
const path=window.location.pathname;if(path&&path!=='/'&&path!=='/home'&&path!=='/'){window._initialPath=path;}
const pageId=ROUTES[path];if(pageId&&pageId!=='home'){window._initialRoute=pageId;}
document.querySelectorAll('.comments-section').forEach(function(c){c.classList.remove('open');});});window.navigateTo=navigateTo;(function(){var params=new URLSearchParams(window.location.search);var postId=params.get('p');if(!postId)return;try{var cleanUrl=window.location.origin+window.location.pathname;window.history.replaceState(null,'',cleanUrl);}catch(e){}
function _tryOpenFBLink(tries){if(tries<=0)return;if(postId){if(typeof scrollToPost==='function'){gp&&gp('home');setTimeout(function(){scrollToPost(postId);},600);return;}}
setTimeout(function(){_tryOpenFBLink(tries-1);},700);}
window._fbDeepLink={postId:postId};document.addEventListener('DOMContentLoaded',function(){setTimeout(function(){_tryOpenFBLink(8);},1500);});})();window.gp=(id,pushState=true)=>{const currentPage=document.querySelector('.page.active');if(currentPage&&currentPage.id==='page-userprofile'&&id!=='userprofile'){_stopShopParticles();if(_equippedItems?.efecto)setTimeout(()=>_startShopParticles(_equippedItems.efecto),100);if(window._upPostsUnsub){window._upPostsUnsub();window._upPostsUnsub=null;}}
document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const pg=document.getElementById('page-'+id);if(!pg)return;pg.classList.add('active');window.scrollTo(0,0);const siteFooter=document.getElementById('siteFooter');if(siteFooter){siteFooter.style.display=(id==='match')?'none':'block';}
navigateTo(id,pushState);if(id==='profile')renderProfile();if(id==='match'){if(typeof window.initMatchPage==='function')window.initMatchPage();}
if(id==='fotos'){if(typeof window.initFotosPage==='function')setTimeout(window.initFotosPage,50);}
if(id==='admin'){loadAdminData();loadPezSemana();loadSoporteBadge();}
const pvBtn=document.getElementById('postVideoBtn');if(pvBtn)pvBtn.style.display=window.CU?.verified?'flex':'none';if(id==='spots'){loadSpots();loadFriendSpots();}
if(id==='compartir-spot'){spLoadData().then(()=>{spRenderHome();});const isAdmin=window.CU?.nick==='ruizgustavo12'||window.CU?.nick==='gustavo ruiz'||window.CU?.nick==='gustavoruiz'||window.CU?.email==='synxyes@gmail.com'||window.CU?.role==='admin';const spPub=document.getElementById('spNbPublish');const spAdm=document.getElementById('spNbAdmin');const spPubBtn=document.getElementById('spPubBtn');if(spPub)spPub.style.display=window.CU?'inline-flex':'none';if(spAdm)spAdm.style.display=isAdmin?'inline-flex':'none';if(spPubBtn)spPubBtn.style.display=window.CU?'':'none';}
if(id==='reels'){const prevPg=document.querySelector('.page.active');window._reelsPrevPage=prevPg&&prevPg.id!=='page-reels'?prevPg.id.replace('page-',''):'home';const overlay=document.getElementById('reelsOverlay');if(overlay){overlay.style.display='block';document.body.style.overflow='hidden';}
loadReelsPage();return;}
if(id==='shop'){loadShopDiscount();}
if(id==='parches')loadParches();if(id==='soporte')initSoportePage();if(id==='torneos')loadTorneos();if(id==='ranking-semanal')loadRankingSemanal();if(id==='salas'){if(typeof window.initSalasPage==='function')setTimeout(window.initSalasPage,50);}
if(id==='userprofile'){}
if(typeof updatePresenceActivity==='function')updatePresenceActivity(id);};function setNav(el){document.querySelectorAll('.tb-nav-btn').forEach(b=>b.classList.remove('on'));el.classList.add('on');}
window.setNav=setNav;window.FISH_DB=null;window._fishDbLoaded=false;window._fishDbCallbacks=[];window.loadFishDB=function(cb){if(window._fishDbLoaded){if(cb)cb(window.FISH_DB);return;}
if(cb)window._fishDbCallbacks.push(cb);if(window._fishDbLoading)return;window._fishDbLoading=true;var s=document.createElement('script');s.src='fish_db.js';s.onload=function(){window._fishDbLoaded=true;window._fishDbLoading=false;var cbs=window._fishDbCallbacks.splice(0);cbs.forEach(function(fn){try{fn(window.FISH_DB);}catch(e){}});};s.onerror=function(){window._fishDbLoading=false;console.error('No se pudo cargar fish_db.js');};document.head.appendChild(s);};function _mapImg(f){if(!f.maps||!f.maps.length)return'';return f.maps.map(function(m){return'<img src="'+m.i+'" title="'+m.n+'" style="width:32px;height:22px;object-fit:cover;border-radius:3px;opacity:.85;margin-left:2px;" onerror="this.style.display=\'none\'">';}).join('');}
window.om=id=>{const el=document.getElementById(id);if(!el)return;if(id==='mAuth'){el.style.display='block';}
else if(id==='mMessenger'){el.classList.add('open');document.getElementById('chatBubbleMin').style.display='none';}
else{el.classList.add('open');}
if(false&&id==='mNotif_disabled'&&_notifs.some(n=>!n.read)){_notifs.forEach(n=>n.read=true);if(window.CU)updateDoc(doc(db,'users',window.CU.id),{notifs:_notifs.slice(0,30)}).catch(()=>{});updateNotifBadge();updateMsgBadge();}};window.cm=id=>{const el=document.getElementById(id);if(!el)return;if(id==='mAuth'){el.style.display='none';}
else if(id==='mMessenger'){el.classList.remove('open');}
else{el.classList.remove('open');}};document.querySelectorAll('.mo').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open');}));window._storyGroups=[];function _buildStoryGroups(){const map=new Map();const ordered=[..._stories].reverse();ordered.forEach(s=>{if(!map.has(s.userId)){map.set(s.userId,{userId:s.userId,userNick:s.userNick,userAv:s.userAv,userVerified:s.userVerified||false,stories:[]});}
// ── Carga diferida de módulos de funcionalidad ──
window._appFeaturesLoaded = false;
function _loadAppFeatures(){
  if(window._appFeaturesLoaded) return;
  window._appFeaturesLoaded = true;
  import('./app-features.js').catch(e=>console.error('[MiLatido] app-features load error:',e));
}
if(document.readyState==='loading'){
  document.addEventListener('DOMContentLoaded', _loadAppFeatures);
} else {
  _loadAppFeatures();
}
